DemoTask/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url=reverse_lazy('todo:home'))),
	url(r'^user/', include('UserAccount.urls',namespace='user')),
	url(r'^todo/', include('Todo.urls',namespace='todo')),
    url(r'^admin/', include(admin.site.urls)),
)

Todo/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^$', 'Todo.views.task_page', name='home'),
	url(r'^tasks/$', 'Todo.views.tasks', name='tasks_json'),
	url(r'^create','Todo.views.create_task', name='add_task'),
	url(r'^(?P<tid>\d+)/edit','Todo.views.edit_task', name="edit_task"),
	url(r'^(?P<tid>\d+)/assign','Todo.views.assign_user', name="assign_user"),
	url(r'^(?P<aid>\d+)/delassign','Todo.views.delete_assign_user', name="delete_assign_user"),
	url(r'^ndelete/$', 'Todo.views.ndelete',name="multiple_delete"),
	url(r'^(?P<tid>\d+)/$','Todo.views.task_detail_page', name="task"),
	url(r'^(?P<tid>\d+)/data','Todo.views.task_details', name="task_data"),

	url(r'^comment/add','Todo.views.add_comment', name="add_comment"),
	url(r'^comment/(?P<cid>\d+)/edit','Todo.views.edit_comment', name="edit_comment"),
	url(r'^comment/(?P<cid>\d+)/delete','Todo.views.delete_comment', name="delete_comment"),

)

UserAccount/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^login/', 'UserAccount.views.login', name='login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),
    url(r'^logout/$', 'UserAccount.views.logout', name='logout'),
    url(r'^signup/$', 'UserAccount.views.signup', name='signup'),
)

Todo/models.py
from django.db import models
from datetime import datetime   
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=255,null=True)
    description = models.TextField()
    priority = models.CharField(max_length=1,choices=(('1','Low'),('2','Medium'),('3','High')),default="1")
    status = models.CharField(max_length=1,choices=(('0','Pending'),('1','Done')),default="0")
    due_date = models.DateTimeField(max_length=255,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'task'
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'
   
class Comment(models.Model):
    task = models.ForeignKey(Task)
    description = models.TextField()
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.description
    class Meta:
        db_table = 'comment'
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

class Assigned(models.Model):
    task = models.ForeignKey(Task)
    to = models.ForeignKey(User)
    def __str__(self):
        return str(self.task)
    class Meta:
        db_table = 'assigned_task'
        verbose_name = 'Assigned task'
        verbose_name_plural = 'Assigned tasks'

Todo/views.py
import json
import pytz
import datetime
from django.shortcuts import render
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib import messages
from django.core import serializers
from Todo.models import Task
from Todo.models import Comment
from Todo.models import Assigned


@login_required(login_url=reverse('user:login'))
def task_page(request):
	return render(request,'Todo/tasks.html')

@login_required(login_url=reverse('user:login'))
def tasks(request):
	task_array = self_owned_task(request.user)
	task_array = task_array + assigned_task(request.user)
	return HttpResponse(json.dumps(task_array,cls=DjangoJSONEncoder), content_type="application/json")

@login_required(login_url=reverse('user:login'))
def create_task(request):
  if request.method=='POST': 
  	due_date = string_to_datetime(request.POST.get('date_post'))
   	Task.objects.create(user=request.user,name=request.POST.get('name'),description=request.POST.get('description'),priority=request.POST.get ('priority'),due_date=due_date)
   	return HttpResponseRedirect(reverse('todo:home')) 

@login_required(login_url=reverse('user:login'))
def ndelete(request):
	if request.method == "GET":
		return render(request,'Todo/delete.html')
	else:
		tasks_id = request.POST.getlist('tasks_id')
		for i in tasks_id:
			task = Task.objects.get(id=str(i))
			if task.user == request.user:
				task.delete()
		return HttpResponseRedirect(reverse('todo:home'))


@login_required(login_url=reverse('user:login'))
def task_detail_page(request,tid):
	try:
		task = Task.objects.get(id=tid)
	except (ValueError, ObjectDoesNotExist):
		messages.add_message(request, messages.INFO, 'Incorrect Task Id')
		return HttpResponseRedirect(reverse('todo:home'))
	else:
		if check_task_permission(request,task):
			return render(request,'Todo/edit.html',{'tid' : tid})
		else:
			messages.add_message(request, messages.INFO, 'Incorrect Permission')	
			return HttpResponseRedirect(reverse('todo:home'))



@login_required(login_url=reverse('user:login'))
def task_details(request,tid):
	task = Task.objects.get(id=tid)
	if check_task_permission(request,task):
		resp = {}
		resp['task'] = task_dictionary(task)
		resp['comments'] = get_comment(task)
		resp['assign_user'] = get_assigned_user(task)
		return HttpResponse(json.dumps(resp,cls=DjangoJSONEncoder), content_type="application/json")
	else:
		messages.add_message(request, messages.INFO, 'Incorrect Permission')
		return HttpResponseRedirect(reverse('todo:home'))

@login_required(login_url=reverse('user:login'))
def edit_task(request,tid):
	if request.method == "POST":
		task = Task.objects.get(id=tid)
		if check_task_permission(request,task):
			# print request.POST
			task.priority = request.POST.get('priority')
			task.status = request.POST.get('status')
			if request.POST.get('due_date').find('-') < 0:
				task.due_date = string_to_datetime(request.POST.get('due_date'))
			task.save()
			return HttpResponseRedirect(reverse('todo:home')+str(tid)+'/')
		else:
			messages.add_message(request, messages.INFO, 'Incorrect Permission')
			return HttpResponseRedirect(reverse('todo:home'))


@login_required(login_url=reverse('user:login'))
def assign_user(request,tid):
	if request.method == "POST":
		task = Task.objects.get(id=tid)
		if check_task_permission(request,task):
			status,user = get_user(request.POST.get('user_name'))
			if status:
				if not(is_already_assigned(user,task)):
					Assigned.objects.create(task=task,to=user)
			else:
				messages.add_message(request, messages.INFO, 'Username doesnot exists. Please assign task to different user')
			return HttpResponseRedirect(reverse('todo:home')+str(tid)+'/')
		else:
			messages.add_message(request, messages.INFO, 'Incorrect Permission')
			return HttpResponseRedirect(reverse('todo:home'))

@login_required(login_url=reverse('user:login'))
def delete_assign_user(request,aid):
	if request.method == "GET":
		assigned_task = Assigned.objects.get(id=aid)
		tid = assigned_task.task.id
		assigned_task.delete()
		return HttpResponseRedirect(reverse('todo:home')+str(tid)+'/')
	else:
		messages.add_message(request, messages.INFO, 'Incorrect Permission')
		return HttpResponseRedirect(reverse('todo:home'))


@login_required(login_url=reverse('user:login'))
def add_comment(request):
	tid = request.POST.get('task_id')
	task = Task.objects.get(id=tid)
	if task.user == request.user:
		message = request.POST.get('message')
		Comment.objects.create(user=request.user,task=task,description=message)
		return HttpResponseRedirect(reverse('todo:home')+tid+'/')
	else:
		messages.add_message(request, messages.INFO, 'Incorrect Permission')
		return HttpResponseRedirect(reverse('todo:home'))	

@login_required(login_url=reverse('user:login'))
def add_comment(request):
	tid = request.POST.get('task_id')
	task = Task.objects.get(id=tid)
	message = request.POST.get('message')
	Comment.objects.create(user=request.user,task=task,description=message)
	return HttpResponseRedirect(reverse('todo:home')+tid+'/')


@login_required(login_url=reverse('user:login'))
def delete_comment(request,cid):
	comment = Comment.objects.get(id=cid)
	task = comment.task
	if comment.user == request.user or task.user == request.user:
		comment.delete()
		tid = task.id
		return HttpResponseRedirect(reverse('todo:home')+str(tid)+'/')
	else:
		messages.add_message(request, messages.INFO, 'Incorrect Permission')
		return HttpResponseRedirect(reverse('todo:home'))

@login_required(login_url=reverse('user:login'))
def edit_comment(request,cid):
	if request.method == "GET":
		comment = Comment.objects.get(id=cid)
		if comment.user == request.user:
			desc = comment.description
			return render(request,'Todo/edit_comment.html',{'id':cid,'desc':desc})
		return HttpResponseRedirect(reverse('todo:home'))
	else:
		comment = Comment.objects.get(id=cid)
		tid = comment.task.id
		comment.description = request.POST.get('message')
		comment.save()
		return HttpResponseRedirect(reverse('todo:home')+str(tid)+'/')


# Helper Function
# ==================

def check_task_permission(request,task):
	if task.user == request.user:
		return True
	assigned_tasks = Assigned.objects.filter(task=task)
	for i in assigned_tasks:
		if i.to == request.user:
			return True
	return False

def task_dictionary(task):
	temp = {}
   	temp["id"] = task.id
   	temp["user"] = task.user.username
   	temp["name"] = task.name
   	temp["status"] = task.status
   	temp["due_date"] = local_date_time(task.due_date) 
   	temp["priority"] = task.priority
   	temp["description"] = task.description
   	temp["timestamp"]= local_date_time(task.timestamp)
   	temp["count"]= comment_count(task)
   	return temp

def self_owned_task(user):
	tasks = Task.objects.filter(user=user)
	task_array = []
  	for i in tasks:
  		task_dic = task_dictionary(i)
   		task_array.append(task_dic)
  	return task_array

def comment_count(task):
	comments = Comment.objects.filter(task=task)
	return comments.count()

def assigned_task(user):
	task_array = []
	for i in Assigned.objects.filter(to=user):
		task = i.task
		if i.to == task.user:
			continue
   		task_dic = task_dictionary(task)
   		task_array.append(task_dic)
   	return task_array

def get_user(username):
	try:
		user = User.objects.get(username=username)
	except (ValueError, ObjectDoesNotExist):
		return False,''
	else:
		return True,user

def is_already_assigned(user,task):
	assigned = Assigned.objects.filter(task=task)
	for i in assigned:
		if i.to == user:
			return True
	return False

def local_date_time(date_time):
	date_time = date_time.replace(tzinfo=pytz.utc) + datetime.timedelta(hours=5, minutes=30)
	date_time = date_time.strftime("%Y-%m-%d %I:%M %p")
	return date_time

def string_to_datetime(string):
	date_time = datetime.datetime.strptime(string,'%m/%d/%Y %I:%M %p')
	ist = pytz.timezone('Asia/Kolkata')
	date_time = ist.localize(date_time)
	return date_time


def get_comment(task):
	comments = []
	for i in Comment.objects.filter(task=task):
		comment = {}
		comment["id"] = i.id
		comment["description"] = i.description
		comment["timestamp"] = local_date_time(i.timestamp)
		comment["user"] = str(i.user)
		comments.append(comment)
	return comments

def get_assigned_user(task):
	assign_user = []
	for i in Assigned.objects.filter(task=task):
		temp={}
   		temp["user"]= str(i.to)
   		temp["id"]=i.id	
   		assign_user.append(temp)
	return assign_user

templates/Todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href= "{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script> 
    <!-- Custom styles for this template -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
	  <!-- Datatable and Datepicker styles for this template -->
	  <link href="http://cdn.datatables.net/1.10.0/css/jquery.dataTables.css" rel="stylesheet">
	  <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include 'Todo/navbar.html' %}
    {% block section %}{% endblock %}
    <!-- Modal for creating Task-->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"  >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title" id="myModalLabel">Create Task</h2>
          </div>
          <div class="modal-body">
            <div class="container">
              <div class="row">
                <div class="col-md-8">
                  <form class="form-horizontal" method="POST" action="/todo/create" onsubmit="return validateName(this)"> 
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="name"  class="col-sm-2 control-label">Task Name</label>
                      <div class="col-sm-6">
                        <input id="name" name="name" type="text" class="form-control" placeholder="Enter Task Name..." onkeyup="validateName();"><label id="nameMe"></label>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="email" class="col-sm-2 control-label">Description</label>
                      <div class="col-sm-6">
                        <textarea  class="form-control" name="description" placeholder="Briefly describe your task..."></textarea>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="password" class="col-sm-2 control-label">Due Date</label>
                      <div class='input-group date col-sm-6' id='stop'>
                        <input style="background:#fff" name="date_post" type='text' class="form-control"  id="datebox"/>
                        <span  class="input-group-addon" id="calendar"><span class="glyphicon glyphicon-calendar"></span>
                        </span>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="city" class="col-sm-2 control-label">Priority</label>
                      <div class="col-sm-6">
                        <select class="form-control" name="priority">
                          <option value="3">High</option>
                          <option value="2">Medium</option>
					                <option value="1">Low</option>
                        </select>
                      </div>
                    </div>
							      <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-6">
                        <button type="submit" class="btn btn-success" >Add Task</button>
                        <button type="reset" class="btn btn-default"  data-dismiss="modal" aria-hidden="true">Close</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.modal -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.js"></script>
	  <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
	  {% block js %}
    {% endblock %}
    <script type="text/javascript">
    $('#datebox').focus(function()
         {
     
     $('#calendar').click();
     
     });
    </script>
    <script>
      $(function () {
        $('#start').datetimepicker();
        $('#stop').datetimepicker();
      });
    </script>
  </body>
</html>

templates/Todo/delete.html
{% extends "Todo/base.html" %}
{% block title %}Delete Tasks: Todo Lists{% endblock %}
{% block section %}
<section id="main-content">
         <section class="wrapper">
            <div class="col-sm-10 col-sm-offset-1">
               <h1>Delete Tasks</h1>
               <section class="panel panel-table" >
                  <div class="panel-body">
                     <div class="adv-table delete-table">
                        <form role="form" method="post" action="">
                           {% csrf_token %}
                           <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered " id="task">
                              <thead class="panel-table-head">
                                 <tr>
                                    <th>Name</th>
                                    <th>Owner</th>
                                    <th class="">Created On</th>
                                    <th class="">Due Date</th>
                                    <th class="">Delete</th>
                                 </tr>
                              </thead>
                              <tbody id="task-body">
                              </tbody>
                           </table>
                           <center>
                              <input class="btn btn-danger" type="submit" value="delete">
                           </center>
                        </form>
                        
                     </div>
                  </div>
               </section>
            </div>
            </div>
            <!-- page end-->
         </section>
</section>
{% endblock %}
{% block js %}
<script src="{{STATIC_URL}}js/delete.js"></script>
{% endblock %}
 

templates/Todo/edit.html
{% extends "Todo/base.html" %}
{% block title %}Delete Tasks: Todo Lists{% endblock %}
{% block section %}
<div class="container">
         <div class="col-sm-10 col-sm-offset-1">
            {% if messages %}
                        {% for message in messages %}
                           <div class="alert alert-danger alert-dismissable">
                              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                              <h6>{{message|safe}}</h6>
                           </div>
                        {% endfor %}
            {% endif %}
            <div class="widget stacked widget-table action-table">
               <form class="form-horizontal" method="POST" action="{% url 'todo:home' %}{{tid}}/edit">
                  {% csrf_token %}
                  <div class="widget-header">
                     <h1 id="task_name" ></h1>
                     <p class="pull-right"><span style="padding:5px"></span><button type="submit" class="btn btn-default" >Save</button></p>
                  </div>
                  <div class="widget-content">
                     <table id="task"class="table table-striped table-bordered">
                        <tbody id="task-body" >
                           <tr id="user">
                              <td>Owner</td>
                           </tr>
                           <tr id="text">
                              <td>Description</td>
                           </tr>
                           <tr id="timestamp">
                              <td>Created On</td>
                           </tr>
                           <tr id="due_date">
                              <td>Due Date</td>
                              <td>
                                 <div  style="padding:0px;" class="input-group date col-sm-4 pull-left" id="stop1"><input name="due_date" style="background:#fff;" type="text" class="form-control date" value="" id="datetimebox"/><span class="input-group-addon"><span class="glyphicon glyphicon-calendar" id="calendar-icon"></span></span></div>
                              </td>
                           </tr>
                           <tr id="status">
                              <td>Status</td>
                           </tr>
                           <tr id="assign">
                              <td>AssignedTo</td>
                           </tr>
                           <tr id="priority">
                              <td>Priority</td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
                  <!-- /widget-content -->
               </form>
            </div>
            <!-- /widget -->
         </div>
         <!-- container -->
</div>
<br>
<div class="container">
         <div class="col-sm-8 col-sm-offset-1">
            <div id="controls">
               <form role="form" action="/todo/comment/add" method="post" >{% csrf_token %}
                  <textarea placeholder="Write comment here...." rows="5" name="message" id="textbox" cols="80" class="ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true"></textarea>
                  <input type="hidden" name="task_id" value="{{tid}}">
                  <span ><button style="margin-top:10px" class="btn btn-default" type="submit" id="button">Comment</button></span><br>
               </form>
            </div>
         </div>
</div>
<br/>
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
            <div class="modal-content">
               <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h2 class="modal-title" id="myModalLabel">AssignTo</h2>
               </div>
               <div class="modal-body">
                  <div class="container">
                     <div class="row">
                        <div class="col-md-8">
                           <form class="form-horizontal" role="form" method="POST" action="{% url 'todo:home' %}{{tid}}/assign">
                              {% csrf_token %}                
                              <div class="form-group">
                                 <label for="name" class="col-sm-2 control-label"> Name</label>
                                 <div class="col-sm-6">
                                    <input id="div1" name="user_name" type="text" class="form-control" placeholder="Enter user Name..."/>                             
                                 </div>
                              </div>
                              <div class="form-group">
                                 <div class="col-sm-offset-2 col-sm-6">
                                    <button id="add" type="submit" class="btn btn-success" action="{% url 'todo:home' %}{{tid}}/assign">Assign</button>
                                    <button type="reset" class="btn btn-default"  data-dismiss="modal" aria-hidden="true">Close</button>
                                 </div>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
   </div>
</div>
<input type="hidden" name="tid" value={{tid}} id="tid">      
<div class="container">
   <div class= "col-sm-8 col-sm-offset-1">
            <div class="panel panel-default widget" id="comment_pannel">
               <div class="panel-heading">
                  <span class="glyphicon glyphicon-comment"></span>
                  <h3 class="panel-title">
                     Comments
                  </h3>
               </div>
               <div class="panel-body">
                  <ul id ="comments" class="list-group">
                  </ul>
               </div>
            </div>
   </div>
</div>
{% endblock %}
{% block js %}
<script src="{{STATIC_URL}}js/edit.js"></script>
    <script>
      $(function () {
        $('#start').datetimepicker();
        $('#stop1').datetimepicker();
      });
      $('#datetimebox').focus(function()
         {
     
     $('#calendar-icon').click();
     
     });
    </script>
{% endblock %}

templates/Todo/edit_comment.html
{% extends "Todo/base.html" %}
{% block title %}Edit Comment: Todo Lists{% endblock %}
{% block section %}
<div class="container">
         <div class="col-sm-8 col-sm-offset-1">
            <div id="controls">
               <form role="form" action="/todo/comment/{{id}}/edit" method="post">{% csrf_token %}
                  <label style="font-size:26px" for="name"  class="control-label">Update your comment</label>
                  <textarea placeholder="" rows="5" name="message" id="textbox" cols="60" class="ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">{{desc}}</textarea>
                  <input type="hidden" name="id" value="{{id}}">
                  <span ><button style="margin-top:10px" class="btn btn-default" type="submit" id="button">Modify</button></span><br>
               </form>
            </div>
         </div>
</div>
{% endblock %}

templates/Todo/navbar.html
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'todo:home' %}">TODOLIST</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav ">
        <li><a data-toggle="modal" data-target="#myModal" href="#myModal">CREATE</a></li>
        <li><a href="{% url 'todo:multiple_delete' %}">DELETE</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li ><a  href="{% url 'user:logout' %}">LOGOUT</a></li>
      </ul>
    </div>
  </div>
</div>
      

templates/Todo/tasks.html
{% extends "Todo/base.html" %}
{% block title %}Tasks: Todo Lists{% endblock %}
{% block section %}
<section id="main-content">
         <section class="wrapper">
               <div class="col-sm-10 col-sm-offset-1">
                  <h1><span class="fa fa-edit">Task</span></h1>
                  <section class="panel panel-table" >
                     <div class="panel-body">
                     {% if messages %}
                        {% for message in messages %}
                           <div class="alert alert-info alert-dismissable">
                              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                              <h6>{{message|safe}}</h6>
                           </div>
                        {% endfor %}
                     {% endif %}
                        <div  class="adv-table task-table">
                           <table  class="table table-bordered table-responsive " id="task">
                              <thead class="panel-table-head">
                                 <tr>
                                    <th>Name</th>
                                    <th>Owner</th>
                                    <th>Created On</th>
                                    <th>Due Date</th>
                                    <th>Status</th>
                                    <th>Priority</th>
                                    <th>Comments</th>
                                 </tr>
                              </thead>
                              <tbody id="task-body">    
                              </tbody>
                           </table>
                        </div>
                     </div>
                  </section>
               </div>          
         </section>
</section>
{% endblock %}
{% block js %}
<script src="{{STATIC_URL}}js/tasks.js"></script>
{% endblock %}      